# Generated by Django 5.2.4 on 2025-07-16 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_payment_paymentitem_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.order'),
        ),
        migrations.AlterField(
            model_name='paymentitem',
            name='order_item_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.orderitem'),
        ),
    ]
