# Generated by Django 5.2.4 on 2025-07-16 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_payment_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='paymentitem',
            old_name='order_item_id',
            new_name='order_item',
        ),
        migrations.RenameField(
            model_name='paymentitem',
            old_name='payment_id',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='payment_id',
            new_name='payment',
        ),
    ]
