# Generated by Django 5.2.4 on 2025-07-16 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_cart_id_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
