# WEEK 4 Exercises - Making Queries

![ERD-E-COMMERCE](./images/ERD-week4-exercise.png)

## Instruction

1. สร้าง `virtual environment`
2. ติดตั้ง `django` และ `psycopg2` libraries
3. สร้างโปรเจคใหม่ใหม่ชื่อ`myshop`
4. จากนั้นให้ทำการ startapp ใหม่ชื่อ `shop`
5. สร้าง database ชื่อ `shop` ใน Postgres DB
6. ทำการเพิ่ม code ด้านล่างนี้ในไฟล์ `shop/models.py`
7. เพิ่ม **'shop'** ใน `settings.py`
8. ทำการ `makemigrations` และ `migrate`


```python
from django.db import models

# Create your models here.
class Customer(models.Model):
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=200)
    email = models.CharField(max_length=150)
    address = models.JSONField(null=True)

class ProductCategory(models.Model):
    name = models.CharField(max_length=150)

class Product(models.Model):
    name = models.CharField(max_length=150)
    description = models.TextField(null=True, blank=True)
    remaining_amount = models.PositiveIntegerField(default=0)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    categories = models.ManyToManyField(ProductCategory)

class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    create_date = models.DateTimeField()
    expired_in = models.PositiveIntegerField(default=60)
    
class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    amount = models.PositiveIntegerField(default=1)
    
class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    order_date = models.DateField()
    remark = models.TextField(null=True, blank=True)

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    amount = models.PositiveIntegerField(default=1)
    
class Payment(models.Model):
    order = models.OneToOneField(Order, on_delete=models.PROTECT)
    payment_date = models.DateField()
    remark = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    discount = models.DecimalField(max_digits=10, decimal_places=2, default=0)

class PaymentItem(models.Model):
    payment = models.ForeignKey(Payment, on_delete=models.CASCADE)
    order_item = models.OneToOneField(OrderItem, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    discount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    
class PaymentMethod(models.Model):
    class MethodChoices(models.Choices):
        QR = "QR"
        CREDIT = "CREDIT"
    
    payment = models.ForeignKey(Payment, on_delete=models.CASCADE)
    method = models.CharField(max_length=15, choices=MethodChoices.choices)
    price = models.DecimalField(max_digits=10, decimal_places=2)
```


**จากนั้นให้ทำการ migrate และ run คำสั่งในไฟล์ `shop.sql` ใน PgAdmin4**

In [1]:
import os
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"

### 1. ให้นักศึกษา Query ค้นหาข้อมูลมาแสดงให้ถูกต้องตามโจทย์

1.1 query หาข้อมูล `Order` ทั้งหมดที่เกิดขึ้นในเดือน `พฤษภาคม` มาแสดงผล 10 รายการแรก และแสดงผลดังตัวอย่าง (0.25 คะแนน)

```txt
ORDER ID:22, DATE: 2024-05-01, 
ORDER ID:23, DATE: 2024-05-01, 
ORDER ID:24, DATE: 2024-05-01, 
ORDER ID:25, DATE: 2024-05-02, 
ORDER ID:26, DATE: 2024-05-02, 
ORDER ID:27, DATE: 2024-05-02, 
ORDER ID:28, DATE: 2024-05-03, 
ORDER ID:29, DATE: 2024-05-03, 
ORDER ID:30, DATE: 2024-05-03, 
ORDER ID:31, DATE: 2024-05-04, 
```

In [2]:
Order.objects.all()

<QuerySet [<Order: Order object (1)>, <Order: Order object (2)>, <Order: Order object (3)>, <Order: Order object (4)>, <Order: Order object (5)>, <Order: Order object (6)>, <Order: Order object (7)>, <Order: Order object (8)>, <Order: Order object (9)>, <Order: Order object (10)>, <Order: Order object (11)>, <Order: Order object (12)>, <Order: Order object (13)>, <Order: Order object (14)>, <Order: Order object (15)>, <Order: Order object (16)>, <Order: Order object (17)>, <Order: Order object (18)>, <Order: Order object (19)>, <Order: Order object (20)>, '...(remaining elements truncated)...']>

In [3]:
from shop.models import Order

for order in Order.objects.filter(order_date__month=5)[:10]:
    print('ORDER ID:', order.id, ', DATE:',  order.order_date, "," , end='')
    print()

ORDER ID: 22 , DATE: 2024-05-01 ,
ORDER ID: 23 , DATE: 2024-05-01 ,
ORDER ID: 24 , DATE: 2024-05-01 ,
ORDER ID: 25 , DATE: 2024-05-02 ,
ORDER ID: 26 , DATE: 2024-05-02 ,
ORDER ID: 27 , DATE: 2024-05-02 ,
ORDER ID: 28 , DATE: 2024-05-03 ,
ORDER ID: 29 , DATE: 2024-05-03 ,
ORDER ID: 30 , DATE: 2024-05-03 ,
ORDER ID: 31 , DATE: 2024-05-04 ,


1.2 query หาข้อมูล `Order` ที่มีการซื้อสินค้าชื่อ "Dog Bed" (ดูที่รายการ `OrderItem`) และแสดงผลดังตัวอย่าง (0.25 คะแนน)

```txt
# ตัวอย่างบางส่วน
ORDER ID: 8, ORDER_DATE: 2024-04-26, CUSTOMER: Suwichada Jarastham, REMARK: None
```

In [13]:
from shop.models import Order, OrderItem

f = Order.objects.filter(orderitem__product__name__contains="Dog Bed")
# join table เพราะจะหาคำตามนี้

for i in f:
    print(f"ORDER ID: {i.id}, ORDER_DATE: {i.order_date}, CUSTOMER: {i.customer.first_name} {i.customer.last_name}, REMARK: {i.remark}")
    # เข้าถึงตาราง customer ได้เลยแบบไม่ต้อง join

ORDER ID: 8, ORDER_DATE: 2024-04-26, CUSTOMER: Suwichada Jarastham, REMARK: None
ORDER ID: 16, ORDER_DATE: 2024-04-29, CUSTOMER: Trinnapon Yinggnam, REMARK: None
ORDER ID: 23, ORDER_DATE: 2024-05-01, CUSTOMER: Warit Pititat, REMARK: None
ORDER ID: 36, ORDER_DATE: 2024-05-05, CUSTOMER: Manit Senapan, REMARK: None
ORDER ID: 63, ORDER_DATE: 2024-05-14, CUSTOMER: Dejwit Tangjareonsakul, REMARK: None
ORDER ID: 79, ORDER_DATE: 2024-05-20, CUSTOMER: Techathorn Sriwanwilai, REMARK: None
ORDER ID: 151, ORDER_DATE: 2024-06-13, CUSTOMER: Thitirat Sukkesorn, REMARK: None


1.3 query หาข้อมูล `Product` ที่มีราคาสินค้าตั้งแต่ `5000.00` ขึ้นไป และอยู่ในหมวดหมู่ `Information Technology` และแสดงผลดังตัวอย่าง (0.25 คะแนน)

```txt
# ตัวอย่างบางส่วน 
PRODUCT ID: 1, NAME: Smartphone, PRICE: 5900.00
```

In [19]:
from shop.models import Product



for product in Product.objects.filter(price__gte=5000, categories__name = 'Information Technology'):
    print(f"PRODUCT ID: {product.id}, NAME: {product.name}, PRICE: {product.price}")

PRODUCT ID: 1, NAME: Smartphone, PRICE: 5900.00
PRODUCT ID: 2, NAME: Laptop, PRICE: 25999.00
PRODUCT ID: 3, NAME: Smart TV, PRICE: 8900.00
PRODUCT ID: 5, NAME: Tablet, PRICE: 12900.00
PRODUCT ID: 7, NAME: Digital Camera, PRICE: 32000.00
PRODUCT ID: 11, NAME: Refrigerator, PRICE: 9000.00
PRODUCT ID: 14, NAME: Air Conditioner, PRICE: 18900.00
PRODUCT ID: 31, NAME: Sofa, PRICE: 7000.00
PRODUCT ID: 54, NAME: Automatic Pet Feeder, PRICE: 7900.00
PRODUCT ID: 61, NAME: Diamond Stud Earrings, PRICE: 320000.00
PRODUCT ID: 62, NAME: Silver Charm Bracelet, PRICE: 70000.00
PRODUCT ID: 63, NAME: Gold Pendant Necklace, PRICE: 59000.00
PRODUCT ID: 64, NAME: Gemstone Ring, PRICE: 9000.00
PRODUCT ID: 65, NAME: Rose Gold Hoop Earrings, PRICE: 1200000.00


1.4 query หาข้อมูล `Product` ที่มีราคาสินค้าน้อยกว่า `200.00` และมากกว่า `100.00` และแสดงผลดังตัวอย่าง (0.25 คะแนน)

```txt
PRODUCT ID: 28, NAME: Women's Sweater, PRICE: 190.00
PRODUCT ID: 66, NAME: Salvage the Bones, PRICE: 129.00
```

In [46]:
from shop.models import Product

for product in Product.objects.filter(price__lt=200, price__gt=100):
    print(f"PRODUCT ID: {product.id}, NAME: {product.name}, PRICE: {product.price}")

PRODUCT ID: 28, NAME: Women's Sweater, PRICE: 190.00
PRODUCT ID: 66, NAME: Salvage the Bones, PRICE: 129.00


1.5 query หาข้อมูล `Product` ในหมวดหมู่ `Electronics` หรือ `Toys and Games` ที่มีราคามากกว่าหรือเท่ากับ 10,000 หรือมีจำนวนคงเหลือน้อยกว่าหรือเท่ากับ 10 และแสดงผลดังตัวอย่าง (0.25 คะแนน)

```txt
# ตัวอย่างบางส่วน 
PRODUCT ID: 2,	PRICE: 25999.00, REMAINING: 19, CATEGORIES: Information Technology, Electronics
PRODUCT ID: 3,	PRICE: 8900.00, REMAINING: 10, CATEGORIES: Information Technology, Electronics
PRODUCT ID: 6,	PRICE: 5000.00, REMAINING: 10, CATEGORIES: Information Technology, Electronics
PRODUCT ID: 7,	PRICE: 32000.00, REMAINING: 4, CATEGORIES: Information Technology, Electronics
PRODUCT ID: 8,	PRICE: 990.00, REMAINING: 0, CATEGORIES: Information Technology, Electronics
PRODUCT ID: 8,	PRICE: 990.00, REMAINING: 0, CATEGORIES: Information Technology, Electronics
```

In [92]:
products = Product.objects.filter(Q(categories__name='Electronics')|Q(categories__name='Toys and Games'), Q(price__gte=10000) | Q(remaining_amount__lte=10))

for product in products:
    print(f"PRODUCT ID: {product.id}, PRICE: {product.price}, REMAINING: {product.remaining_amount}, CATEGORIES: ", end='')
    for i in product.categories.all():
        print(f"{i.name}, ", end='')
    print()


PRODUCT ID: 2, PRICE: 25999.00, REMAINING: 19, CATEGORIES: Information Technology, Electronics, 
PRODUCT ID: 3, PRICE: 8900.00, REMAINING: 10, CATEGORIES: Information Technology, Electronics, 
PRODUCT ID: 5, PRICE: 12900.00, REMAINING: 22, CATEGORIES: Information Technology, Electronics, 
PRODUCT ID: 6, PRICE: 5000.00, REMAINING: 10, CATEGORIES: Information Technology, Electronics, 
PRODUCT ID: 7, PRICE: 32000.00, REMAINING: 4, CATEGORIES: Information Technology, Electronics, 
PRODUCT ID: 8, PRICE: 990.00, REMAINING: 0, CATEGORIES: Information Technology, Electronics, 
PRODUCT ID: 14, PRICE: 18900.00, REMAINING: 30, CATEGORIES: Electronics, 
PRODUCT ID: 50, PRICE: 500.00, REMAINING: 10, CATEGORIES: Toys and Games, 


1.6 query หาข้อมูล Product โดยมีเงื่อนไขดังนี้: (0.25 คะแนน)

- ชื่อสินค้ามีคำว่า `Smart` หรือ `Electric`
- รายละเอียดสินค้า ไม่มีคำว่า `compact` หรือ `portable`
- รายละเอียดสินค้ามีชื่อสินค้า

และแสดงผลดังตัวอย่าง
```txt
PRODUCT ID: 1, NAME: Smartphone, DESCRIPTION: A sleek and powerful smartphone with advanced features. 
PRODUCT ID: 10, NAME: Smartwatch, DESCRIPTION: A stylish smartwatch with health monitoring and notification features. 
PRODUCT ID: 16, NAME: Electric Kettle, DESCRIPTION: Fast-boiling electric kettle with auto shut-off feature. 
PRODUCT ID: 18, NAME: Electric Fan, DESCRIPTION: Oscillating electric fan for cooling rooms. 
```

In [121]:
from django.db.models import F


a = Product.objects.filter(
    (Q(name__contains='Electric') | Q(name__contains='Smart')), Q(description__icontains=F("name")
    )).exclude(Q(description__contains='compact') | Q(description__contains='portable'))

for product in a:
    print(f"PRODUCT ID: {product.id}, NAME: {product.name}, DESCRIPTION: {product.description}")


PRODUCT ID: 1, NAME: Smartphone, DESCRIPTION: A sleek and powerful smartphone with advanced features.
PRODUCT ID: 10, NAME: Smartwatch, DESCRIPTION: A stylish smartwatch with health monitoring and notification features.
PRODUCT ID: 16, NAME: Electric Kettle, DESCRIPTION: Fast-boiling electric kettle with auto shut-off feature.
PRODUCT ID: 18, NAME: Electric Fan, DESCRIPTION: Oscillating electric fan for cooling rooms.


### 2. เพิ่ม ลบ แก้ไข สินค้า

2.1 ให้เพิ่มสินค้าใหม่จำนวน 3 รายการ (0.1 คะแนน)

```txt
สินค้าที่ 1
ชื่อ: Philosopher's Stone (1997)
หมวดหมู่สินค้า: Books and Media
จำนวนคงเหลือ: 20
รายละเอียดซ: By J. K. Rowling.
ราคา: 790

สินค้าที่ 2
ชื่อ: Me Before You
หมวดหมู่สินค้า: Books and Media
จำนวนคงเหลือ: 40
รายละเอียดซ: A romance novel written by Jojo
ราคา: 390

สินค้าที่ 3
ชื่อ: Notebook HP Pavilion Silver
หมวดหมู่สินค้า: Information Technology และ Electronics
จำนวนคงเหลือ: 10
รายละเอียดซ: Display Screen. 16.0
ราคา: 20000
```

In [123]:
p1 = Product.objects.create(name="Philosopher's Stone (1997)", remaining_amount=20, description='By J. K. Rowling.', price=790)
pc1 = ProductCategory.objects.create(name='Books and Media')

p1.categories.add(pc1)

In [127]:
p2 = Product.objects.create(name="Me Before You", remaining_amount=40, description='A romance novel written by Jojo', price=390)
pc2 = ProductCategory.objects.get(name='Books and Media')

p2.categories.add(pc2)

In [128]:
p3 = Product.objects.create(name="Notebook HP Pavilion Silver", remaining_amount=20, description='Display Screen. 16.0', price=20000)
pc3 = ProductCategory.objects.get(name='Information Technology')
pc4 = ProductCategory.objects.get(name='Electronics')


p3.categories.add(pc3)
p3.categories.add(pc4)

2.2 แก้ไขชื่อสินค้า จาก `Philosopher's Stone (1997)` เป็น `Half-Blood Prince (2005)` (0.1 คะแนน)

In [132]:
p1 = Product.objects.filter(name="Philosopher's Stone (1997)")[0]
p1.name = "Half-Blood Prince (2005)"
p1.save()

2.3 แก้ไขชื่อหมวดหมู่สินค้า จาก `Books and Media` เป็น `Books` (0.1 คะแนน)

In [139]:
pc = ProductCategory.objects.get(name="Books and Media")
pc.name = "Books"
pc.save()

DoesNotExist: ProductCategory matching query does not exist.

2.4 ลบสินค้าทุกตัวที่อยู่ในหมวดหมู่ `Books` (0.2 คะแนน)

In [140]:
Product.objects.filter(categories__name='Books').delete()

(6, {'shop.Product_categories': 3, 'shop.Product': 3})